[project]
name = "automas-dev-github-io"
version = "0.1.0"
description = "https://automas-dev.github.io/"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
]
